services:
  - type: web
    name: kaninkalender
    env: python
    buildCommand: |
      pip install -r requirements.txt
      export FLASK_APP=app.py
      flask db upgrade
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: PASSWORD_HASH
        sync: false
      - key: CALENDAR_TITLE
        value: Kaninkalendern
      - key: RENDER
        value: "true" 