"""add description to task

Revision ID: 39999cf753a0
Revises: e22d69c77e1b
Create Date: 2025-05-11 11:44:07.010635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39999cf753a0'
down_revision = 'e22d69c77e1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ### 