"""Lägg till start_date i Schedule

Revision ID: bccc405b4a66
Revises: f9fc8d4e21ec
Create Date: 2025-05-10 15:18:08.045446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bccc405b4a66'
down_revision = 'f9fc8d4e21ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###
