"""initial schema

Revision ID: f9fc8d4e21ec
Revises: 2921340d8e1c
Create Date: 2025-05-10 14:44:59.403779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9fc8d4e21ec'
down_revision = '2921340d8e1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
